//POST academic-class REQUEST
POST http://localhost:3000/api/v1/academic-class/school
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk

{
    "name": "Test Class",
  "status": "active",
  "school": "645bcac3fdf6ac2225641982",
  "description": "A test class"
}
###
//GET all academic-class REQUEST
GET http://localhost:3000/api/v1/academic-class
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk

###
//GET academic-class by school REQUEST
GET http://localhost:3000/api/v1/academic-class/school?school=645bcac3fdf6ac2225641982
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk

//PUT academic-class update REQUEST
PUT http://localhost:3000/api/v1/academic-class/school
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk

{
    "name": "Test Class",
  "status": "active",
  "school": "645bcac3fdf6ac2225641982",
  "description": "A test class"
}