//POST calender REQUEST
POST http://localhost:3000/api/v1/calender/school
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk

{
  
    "eventStart": "2023-05-23T14:23:00.000Z",
    "eventEnd": "2023-05-23T18:23:00.000Z",
    "eventId": "646ddc97f361e1431efb85a4",
    "eventTitle": "Math101 Lesson",
    "school":"645bcac3fdf6ac2225641982"
}

###
//GET all calender REQUEST
GET http://localhost:3000/api/v1/calender
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk

###
//GET calaender by school REQUEST
GET http://localhost:3000/api/v1/calender/school?school=645bcac3fdf6ac2225641982
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk

###
//DELETE calaender REQUEST
DELETE http://localhost:3000/api/v1/calender/school/646fd07d0d880980855ab7ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk


###
//PUT calender update REQUEST
PUT http://localhost:3000/api/v1/calender/school/646fd07d0d880980855ab7ae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWMzMTUwMGQwZGQ3ZDgzZmJlYmYzNCIsImVtYWlsIjoib2tvcmllaWZlYW55aTR1QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaWZ5bWF0aWNzIiwicm9sZXMiOlt7Il9pZCI6IjY0NWMyZjNiNjI0Y2I4MDQ1YzUxMGUxNiIsIm5hbWUiOiJzdXBlckFkbWluIn1dLCJzY2hvb2wiOltdLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA1LTExVDAwOjA1OjM2LjMyMloiLCJfX3YiOjAsImlhdCI6MTY4NTAwNjY3MCwiZXhwIjoxNjg1MDkzMDcwfQ.ojvYRW8NHqX3YVRXqXmuPM-WCe18X4S2KdxuEF0BUqk

{
 "eventStart": "2023-05-23T14:23:00.000Z",
    "eventEnd": "2023-05-23T18:23:00.000Z",
    "eventId": "646ddc97f361e1431efb85a4",
    "eventTitle": "Math101 Lesson updated"
}